x = input(" Enter Your Number \n ")
print(x)

y = (" * 1 = " + x * 1)
print(x + y)
y = (" * 2 = " + x * 2)
print(x + y)
y = (" * 3 = " + x * 3 )
print(x + y)
y = (" * 4 = " + x)
print(x + y)
y = (" * 5 = " + x)
print(x + y)
y = (" * 6 = " + x)
print(x + y)
y = (" * 7 = " + x)
print(x + y)
y = (" * 8 = " + x)
print(x + y)
y = (" * 9 = " + x)
print(x + y)
y = (" * 10 = " + x)
print(x + y)
